openapi: 3.0.0
info:
  title: Desafio Técnico - API de Gerenciamento de Tarefas
  description: API RESTful para gerenciamento de tarefas (To-Do List) usando NestJS.
  version: 1.0.0

paths:
  /tasks:
    get:
      summary: Listar todas as tarefas do usuário
      tags:
        - Tasks
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [PENDING, COMPLETED]
          description: Filtrar tarefas por status (pendente ou concluída)
      responses:
        '200':
          description: Lista de tarefas retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    status:
                      type: string
                      enum: [PENDING, COMPLETED]
        '404':
          description: Usuário não autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string
                  statusCode:
                    type: integer
        '500':
          description: Erro interno do servidor

    post:
      summary: Criar uma nova tarefa
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
                properties:
                  title:
                      type: string
                  description:
                    type: string
                  status:
                    type: string
                    enum: [PENDING, COMPLETED]
      responses:
        '201':
          description: Tarefa criada com sucesso
          content:
            application/json:
              schema:
                type: object
                  properties:
                    id:
                      type: integer
                    title:
                        type: string
                    description:
                      type: string
                    status:
                      type: string
                      enum: [PENDING, COMPLETED]
                    user:
                      type: object
                      properties:
                        id:
                          type: integer
                        firstName:
                            type: string
                        lastName:
                          type: string
                        email:
                          type: string
        '400':
          description: Requisição inválida
        '404':
          description: Usuário não encontrado
        '500':
          description: Erro interno do servidor

  /tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Obter uma tarefa pelo ID
      tags:
        - Tasks
      responses:
        '200':
          description: Tarefa encontrada
          content:
            application/json:
              schema:
                type: object
                  properties:
                    id:
                      type: integer
                    title:
                        type: string
                    description:
                      type: string
                    status:
                      type: string
                      enum: [PENDING, COMPLETED]
                    user:
                      type: object
                      properties:
                        id:
                          type: integer
                        firstName:
                            type: string
                        lastName:
                          type: string
                        email:
                          type: string
        '404':
          description: Tarefa não encontrada
        '500':
          description: Erro interno do servidor

    put:
      summary: Atualizar uma tarefa pelo ID
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
                properties:
                  title:
                      type: string
                  description:
                    type: string
                  status:
                    type: string
                    enum: [PENDING, COMPLETED]
      responses:
        '200':
          description: Tarefa atualizada com sucesso
        '400':
          description: Requisição inválida
        '404':
          description: Tarefa não encontrada
        '500':
          description: Erro interno do servidor

    delete:
      summary: Excluir uma tarefa pelo ID
      tags:
        - Tasks
      responses:
        '204':
          description: Tarefa excluída com sucesso
        '404':
          description: Tarefa não encontrada
        '500':
          description: Erro interno do servidor

components:
  schemas:
    CreateTaskDto:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [PENDING, COMPLETED]
      required:
        - title
        - description
        - status

    UpdateTaskDto:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [PENDING, COMPLETED]

  Task:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      description:
        type: string
      status:
        type: string
        enum: [PENDING, COMPLETED]
    required:
      - id
      - title
      - description
      - status

security:
  - bearerAuth: []
